#!/bin/bash
echo "=== Database Statistics ==="
echo "Companies:"
docker exec slms-postgres-prod psql -U slms_prod -d slms_production -c "SELECT COUNT(*) FROM companies;"
echo "Users:"
docker exec slms-postgres-prod psql -U slms_prod -d slms_production -c "SELECT COUNT(*) FROM users;"
echo "Shipments:"
docker exec slms-postgres-prod psql -U slms_prod -d slms_production -c "SELECT COUNT(*) FROM shipments;"
echo "Suppliers:"
docker exec slms-postgres-prod psql -U slms_prod -d slms_production -c "SELECT COUNT(*) FROM suppliers;"
echo "Currencies:"
docker exec slms-postgres-prod psql -U slms_prod -d slms_production -c "SELECT COUNT(*) FROM currencies;"
echo "Countries:"
docker exec slms-postgres-prod psql -U slms_prod -d slms_production -c "SELECT COUNT(*) FROM countries;"
echo "Ports:"
docker exec slms-postgres-prod psql -U slms_prod -d slms_production -c "SELECT COUNT(*) FROM ports;"
