@echo off
cd /d c:\projects\slms
echo Stopping containers...
docker-compose down
echo Starting containers...
docker-compose up -d
echo Waiting for services...
timeout /t 15 /nobreak >nul
echo Checking status...
docker-compose ps
echo Done! Check http://localhost:3001
pause