-- Create document_types table for master data management
CREATE TABLE IF NOT EXISTS document_types (
    id SERIAL PRIMARY KEY,
    company_id INTEGER REFERENCES companies(id),
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    name_en VARCHAR(100),
    name_ar VARCHAR(100),
    category VARCHAR(50) DEFAULT 'other',
    description TEXT,
    file_formats TEXT[],
    max_file_size_mb INTEGER DEFAULT 10,
    requires_approval BOOLEAN DEFAULT false,
    approval_levels INTEGER DEFAULT 1,
    requires_expiry BOOLEAN DEFAULT false,
    default_validity_days INTEGER,
    is_confidential BOOLEAN DEFAULT false,
    retention_period_years INTEGER,
    numbering_prefix VARCHAR(20),
    auto_numbering BOOLEAN DEFAULT false,
    requires_version_control BOOLEAN DEFAULT false,
    requires_digital_signature BOOLEAN DEFAULT false,
    applicable_to VARCHAR(50) DEFAULT 'all',
    template_available BOOLEAN DEFAULT false,
    is_mandatory BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    UNIQUE(company_id, code)
);
