/**
 * Financial Posting Engine
 * Unified entry point for all GL (General Ledger) journal postings.
 * Ensures balanced entries, generates entry numbers, and writes to journal_entries + journal_lines.
 */
import pool from '../db';
import { logger } from '../utils/logger';

export interface PostingLine {
  accountId: number;
  accountCode?: string;
  debit: number;
  credit: number;
  description?: string;
  costCenterId?: number;
  projectId?: number;
  partnerType?: string;
  partnerId?: number;
}

export interface PostingRequest {
  companyId: number;
  entryDate: string;
  journalType: string;
  entryType?: string;
  sourceType?: string;
  sourceId?: number;
  sourceNumber?: string;
  description: string;
  descriptionAr?: string;
  currencyId?: number;
  exchangeRate?: number;
  lines: PostingLine[];
  userId: number;
  fiscalYearId?: number;
  isAutoGenerated?: boolean;
}

interface PostingResult {
  success: boolean;
  journalEntryId?: number;
  entryNumber?: string;
  message?: string;
}

interface ReverseRequest {
  journalEntryId: number;
  companyId: number;
  userId: number;
  reason?: string;
}

class FinancialPostingEngine {
  /**
   * Post a journal entry with multiple lines.
   * Validates debit/credit balance before writing.
   */
  async post(request: PostingRequest): Promise<PostingResult> {
    const { companyId, entryDate, journalType, lines, userId, description } = request;

    // Validate balanced entry
    const totalDebit = lines.reduce((sum, l) => sum + (l.debit || 0), 0);
    const totalCredit = lines.reduce((sum, l) => sum + (l.credit || 0), 0);

    if (Math.abs(totalDebit - totalCredit) > 0.01) {
      return {
        success: false,
        message: `Entry is not balanced: Debit=${totalDebit}, Credit=${totalCredit}`,
      };
    }

    if (lines.length < 2) {
      return {
        success: false,
        message: 'Journal entry must have at least 2 lines',
      };
    }

    const client = await pool.connect();
    try {
      await client.query('BEGIN');

      // Generate entry number
      const entryNumber = await this.generateEntryNumber(client, companyId, journalType, entryDate);

      // Insert journal entry header
      const headerResult = await client.query(
        `INSERT INTO journal_entries 
         (company_id, entry_number, entry_date, journal_type, entry_type, 
          source_type, source_id, source_number, description, description_ar,
          currency_id, exchange_rate, total_debit, total_credit,
          status, is_auto_generated, fiscal_year_id, created_by)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, 'posted', $15, $16, $17)
         RETURNING id, entry_number`,
        [
          companyId, entryNumber, entryDate, journalType,
          request.entryType || null, request.sourceType || null,
          request.sourceId || null, request.sourceNumber || null,
          description, request.descriptionAr || null,
          request.currencyId || null, request.exchangeRate || 1,
          totalDebit, totalCredit,
          request.isAutoGenerated || false,
          request.fiscalYearId || null, userId,
        ]
      );

      const journalEntryId = headerResult.rows[0].id;

      // Insert lines
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        await client.query(
          `INSERT INTO journal_lines
           (journal_entry_id, line_number, account_id, debit_amount, credit_amount,
            description, cost_center_id, project_id, partner_type, partner_id)
           VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)`,
          [
            journalEntryId, i + 1, line.accountId,
            line.debit || 0, line.credit || 0,
            line.description || null,
            line.costCenterId || null, line.projectId || null,
            line.partnerType || null, line.partnerId || null,
          ]
        );
      }

      // Update account balances
      for (const line of lines) {
        await client.query(
          `UPDATE chart_of_accounts 
           SET current_balance = COALESCE(current_balance, 0) + $1 - $2,
               updated_at = NOW()
           WHERE id = $3 AND company_id = $4`,
          [line.debit || 0, line.credit || 0, line.accountId, companyId]
        );
      }

      await client.query('COMMIT');

      logger.info(`Posted journal entry ${entryNumber} (${journalType}) for company ${companyId}`);
      return {
        success: true,
        journalEntryId,
        entryNumber: headerResult.rows[0].entry_number,
      };
    } catch (error: any) {
      await client.query('ROLLBACK');
      logger.error('Financial posting failed:', error);
      return { success: false, message: error.message };
    } finally {
      client.release();
    }
  }

  /**
   * Reverse a previously posted journal entry.
   */
  async reverse(request: ReverseRequest): Promise<PostingResult> {
    const { journalEntryId, companyId, userId, reason } = request;

    const client = await pool.connect();
    try {
      await client.query('BEGIN');

      // Get original entry
      const original = await client.query(
        `SELECT * FROM journal_entries WHERE id = $1 AND company_id = $2`,
        [journalEntryId, companyId]
      );

      if (original.rows.length === 0) {
        return { success: false, message: 'Original entry not found' };
      }

      const entry = original.rows[0];

      // Get original lines
      const linesResult = await client.query(
        `SELECT * FROM journal_lines WHERE journal_entry_id = $1 ORDER BY line_number`,
        [journalEntryId]
      );

      // Create reversal lines (swap debit/credit)
      const reversalLines: PostingLine[] = linesResult.rows.map((l: any) => ({
        accountId: l.account_id,
        debit: l.credit_amount || 0,
        credit: l.debit_amount || 0,
        description: `Reversal: ${l.description || ''}`,
        costCenterId: l.cost_center_id,
        projectId: l.project_id,
        partnerType: l.partner_type,
        partnerId: l.partner_id,
      }));

      await client.query('COMMIT');

      // Post reversal as new entry
      const result = await this.post({
        companyId,
        entryDate: new Date().toISOString().split('T')[0],
        journalType: entry.journal_type,
        entryType: `${entry.entry_type}_reversal`,
        sourceType: 'reversal',
        sourceId: journalEntryId,
        sourceNumber: entry.entry_number,
        description: `Reversal of ${entry.entry_number}${reason ? ': ' + reason : ''}`,
        descriptionAr: entry.description_ar ? `عكس ${entry.description_ar}` : undefined,
        currencyId: entry.currency_id,
        exchangeRate: entry.exchange_rate,
        lines: reversalLines,
        userId,
        isAutoGenerated: true,
      });

      // Mark original as reversed
      if (result.success) {
        await pool.query(
          `UPDATE journal_entries SET status = 'reversed', reversed_by_id = $1 WHERE id = $2`,
          [result.journalEntryId, journalEntryId]
        );
      }

      return result;
    } catch (error: any) {
      await client.query('ROLLBACK');
      logger.error('Journal reversal failed:', error);
      return { success: false, message: error.message };
    } finally {
      client.release();
    }
  }

  /**
   * Generate sequential entry number per company and journal type.
   */
  private async generateEntryNumber(
    client: any,
    companyId: number,
    journalType: string,
    entryDate: string
  ): Promise<string> {
    const year = new Date(entryDate).getFullYear();
    const prefix = `${journalType}-${year}`;

    const result = await client.query(
      `SELECT entry_number FROM journal_entries
       WHERE company_id = $1 AND entry_number LIKE $2
       ORDER BY id DESC LIMIT 1`,
      [companyId, `${prefix}-%`]
    );

    let nextNum = 1;
    if (result.rows.length > 0) {
      const lastNum = result.rows[0].entry_number.split('-').pop();
      nextNum = parseInt(lastNum || '0') + 1;
    }

    return `${prefix}-${String(nextNum).padStart(6, '0')}`;
  }
}

export const financialPostingEngine = new FinancialPostingEngine();
