import { useEffect, useState } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import MainLayout from '../../components/layout/MainLayout';
import { withPermission } from '../../utils/withPermission';
import { MenuPermissions } from '../../config/menu.permissions';
import Button from '../../components/ui/Button';
import Input from '../../components/ui/Input';
import { useToast } from '../../contexts/ToastContext';
import apiClient from '../../lib/apiClient';
import WarehouseSelector from '../../components/common/WarehouseSelector';
import CurrencySelector from '../../components/shared/CurrencySelector';
import ExchangeRateField from '../../components/ui/ExchangeRateField';
import { companyStore } from '../../lib/companyStore';
import {
  PlusIcon,
  ArrowLeftIcon,
  CheckCircleIcon,
} from '@heroicons/react/24/outline';

interface ShipmentType {
  id: number;
  code: string;
  name_en: string;
  name_ar: string;
  is_active: boolean;
}

interface City {
  id: number;
  code: string;
  name: string;
  name_ar?: string;
  name_en?: string;
  country_id?: number;
  is_active: boolean;
}

interface Port {
  id: number;
  code: string;
  name: string;
  name_en: string;
  name_ar: string;
  port_type: 'sea' | 'air' | 'land';
  country_id?: number;
  city_id?: number;
  country_name_en?: string;
  country_name_ar?: string;
}

interface Country {
  id: number;
  code: string;
  name: string;
  name_ar?: string;
  name_en?: string;
  is_active?: boolean;
}

interface Project {
  id: number;
  code: string;
  name_en: string;
  name_ar: string;
  project_type: string;
}

interface PurchaseOrder {
  id: number;
  order_number: string;
  vendor_id: number;
  vendor_name?: string;
  vendor_display_name?: string;
  vendor_contract_number?: string;
  project_id: number;
  project_code?: string;
  project_name?: string;
  total_amount: number;
  currency_id?: number;
  currency_code?: string;
  currency_symbol?: string;
  payment_term_id?: number;
  payment_term_name?: string;
  payment_terms_name?: string;
  payment_method_id?: number;
  payment_method_name?: string;
  incoterm?: string;
  delivery_terms_name?: string;
  // Ports and locations (from migration 140)
  origin_country_id?: number;
  origin_city_id?: number;
  destination_country_id?: number;
  destination_city_id?: number;
  port_of_loading_id?: number;
  port_of_loading_text?: string;
  port_of_discharge_id?: number;
  warehouse_id?: number;
  warehouse_name?: string;
  // Items
  items: POItem[];
}

interface POItem {
  id: number;
  item_id: number;
  sku: string;
  name_en: string;
  name_ar: string;
  quantity: number;
  unit_id: number;
  unit_code: string;
  unit_price: number;
}

interface ShipmentForm {
  source_type: 'manual' | 'purchase_order' | 'rfq' | 'contract';
  purchase_order_id: number | null;
  shipment_number: string;
  shipment_type_id: number | '';
  project_id: number | '';
  currency_id: number | '';
  exchange_rate: string;
  incoterm: string;
  bl_no: string;
  awb_no: string;
  // Country-City pairs
  origin_country_id: number | '';
  destination_country_id: number | '';
  origin_location_id: number | '';
  destination_location_id: number | '';
  // Ports - loading is optional with free text
  port_of_loading_id: number | '';
  port_of_loading_text: string; // للكتابة الحرة
  port_of_discharge_id: number | '';
  expected_arrival_date: string;
  warehouse_id: number | null;
  vendor_id: number | null;
  payment_method: string;
  lc_number: string;
  total_amount: number;
  notes: string;
  // Status & Stage (stored as code strings in database)
  status_code: string;
  stage_code: string;
}

function CreateShipmentPage() {
  const router = useRouter();
  const { showToast } = useToast();

  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);
  const [newShipmentId, setNewShipmentId] = useState<number | null>(null);

  const [shipmentTypes, setShipmentTypes] = useState<ShipmentType[]>([]);
  const [countries, setCountries] = useState<Country[]>([]);
  const [cities, setCities] = useState<City[]>([]);
  const [originCities, setOriginCities] = useState<City[]>([]);
  const [destinationCities, setDestinationCities] = useState<City[]>([]);
  const [ports, setPorts] = useState<Port[]>([]);
  const [projects, setProjects] = useState<Project[]>([]);
  const [purchaseOrders, setPurchaseOrders] = useState<PurchaseOrder[]>([]);
  const [selectedPO, setSelectedPO] = useState<PurchaseOrder | null>(null);
  const [poItems, setPOItems] = useState<POItem[]>([]);
  const [autoGeneratedNumber, setAutoGeneratedNumber] = useState<string>('');
  const [shipmentStatuses, setShipmentStatuses] = useState<{id: number; code: string; name_en: string; name_ar: string}[]>([]);
  const [shipmentStages, setShipmentStages] = useState<{id: number; code: string; name_en: string; name_ar: string}[]>([]);

  // Default Saudi Arabia ID (will be set from countries API)
  const SAUDI_ARABIA_CODE = 'SAU';

  const [selectedCurrencyCode, setSelectedCurrencyCode] = useState<string | null>(null);
  const getCompanyId = () => companyStore.getActiveCompanyId();

  const [formData, setFormData] = useState<ShipmentForm>({
    source_type: 'manual',
    purchase_order_id: null,
    shipment_number: '',
    shipment_type_id: '',
    project_id: '',
    currency_id: '',
    exchange_rate: '1',
    incoterm: '',
    bl_no: '',
    awb_no: '',
    origin_country_id: '',
    destination_country_id: '',
    origin_location_id: '',
    destination_location_id: '',
    port_of_loading_id: '',
    port_of_loading_text: '',
    port_of_discharge_id: '',
    expected_arrival_date: '',
    warehouse_id: null,
    vendor_id: null,
    payment_method: '',
    lc_number: '',
    total_amount: 0,
    notes: '',
    status_code: '',
    stage_code: '',
  });

  const [formErrors, setFormErrors] = useState<Record<string, string>>({});

  useEffect(() => {
    fetchLookups();
    previewShipmentNumber();
  }, []);

  const previewShipmentNumber = async () => {
    try {
      const res = await apiClient.get<{ success: boolean; number: string }>('/api/logistics-shipments/preview-number');
      if (res.number) {
        setAutoGeneratedNumber(res.number);
        setFormData(prev => ({ ...prev, shipment_number: res.number }));
      }
    } catch (e) {
      // Silent fail - user can enter manually
    }
  };

  const fetchLookups = async () => {
    try {
      const [typesRes, countriesRes, citiesRes, portsRes, projectsRes, posRes, statusesRes, stagesRes] = await Promise.all([
        apiClient.get<{ success: boolean; data: ShipmentType[] }>('/api/logistics-shipment-types?limit=100', { cache: 'no-store' }),
        apiClient.get<{ success: boolean; data: Country[] }>('/api/master/countries?limit=300', { cache: 'no-store' }),
        apiClient.get<{ success: boolean; data: City[] }>('/api/master/cities?limit=500', { cache: 'no-store' }),
        apiClient.get<{ success: boolean; data: Port[] }>('/api/ports?limit=500', { cache: 'no-store' }).catch(() => ({ data: [] })),
        apiClient.get<{ success: boolean; data: Project[] }>('/api/projects?limit=500&status=active', { cache: 'no-store' }).catch(() => ({ data: [] })),
        apiClient.get<{ success: boolean; data: PurchaseOrder[] }>('/api/procurement/purchase-orders?limit=200&exclude_with_shipments=true', { cache: 'no-store' }).catch(() => ({ data: [] })),
        apiClient.get<{ success: boolean; data: any[] }>('/api/shipment-lifecycle-statuses?limit=100', { cache: 'no-store' }).catch(() => ({ data: [] })),
        apiClient.get<{ success: boolean; data: any[] }>('/api/shipment-stages?limit=100', { cache: 'no-store' }).catch(() => ({ data: [] })),
      ]);
      setShipmentTypes(typesRes.data || []);
      
      // Sort countries and set Saudi Arabia as default for destination
      const countriesList = countriesRes.data || [];
      setCountries(countriesList);
      
      // Find Saudi Arabia and set as default destination country
      const saudiArabia = countriesList.find((c: Country) => c.code === SAUDI_ARABIA_CODE);
      if (saudiArabia) {
        setFormData(prev => ({ ...prev, destination_country_id: saudiArabia.id }));
      }
      
      setCities(citiesRes.data || []);
      setPorts(portsRes.data || []);
      setProjects(projectsRes.data || []);
      setPurchaseOrders(posRes.data || []);
      setShipmentStatuses(statusesRes.data || []);
      setShipmentStages(stagesRes.data || []);
    } catch (e: any) {
      showToast(e?.message || 'Failed to load lookup data', 'error');
    }
  };

  // Fetch cities when origin country changes
  const handleOriginCountryChange = async (countryId: number) => {
    setFormData(prev => ({ ...prev, origin_country_id: countryId, origin_location_id: '' }));
    if (countryId) {
      try {
        const res = await apiClient.get<{ success: boolean; data: City[] }>(
          `/api/master/cities?country_id=${countryId}&limit=200`,
          { cache: 'no-store' }
        );
        setOriginCities(res.data || []);
      } catch (e) {
        setOriginCities([]);
      }
    } else {
      setOriginCities([]);
    }
  };

  // Fetch cities when destination country changes
  const handleDestinationCountryChange = async (countryId: number) => {
    setFormData(prev => ({ ...prev, destination_country_id: countryId, destination_location_id: '' }));
    if (countryId) {
      try {
        const res = await apiClient.get<{ success: boolean; data: City[] }>(
          `/api/master/cities?country_id=${countryId}&limit=200`,
          { cache: 'no-store' }
        );
        setDestinationCities(res.data || []);
      } catch (e) {
        setDestinationCities([]);
      }
    } else {
      setDestinationCities([]);
    }
  };

  // Initialize destination cities for Saudi Arabia on mount
  useEffect(() => {
    const saudiArabia = countries.find((c) => c.code === SAUDI_ARABIA_CODE);
    if (saudiArabia && formData.destination_country_id === saudiArabia.id) {
      handleDestinationCountryChange(saudiArabia.id);
    }
  }, [countries]);

  // جلب بيانات امر الشراء عند اختياره
  const handlePOSelection = async (poId: number) => {
    try {
      const res = await apiClient.get<{ success: boolean; data: PurchaseOrder }>(
        `/api/procurement/purchase-orders/${poId}`,
        { cache: 'no-store' }
      );
      const po = res.data;
      setSelectedPO(po);
      setPOItems(po.items || []);

      // تحميل المدن للبلدان المحددة في امر الشراء
      if (po.origin_country_id) {
        try {
          const citiesRes = await apiClient.get<{ success: boolean; data: City[] }>(
            `/api/master/cities?country_id=${po.origin_country_id}&limit=200`,
            { cache: 'no-store' }
          );
          setOriginCities(citiesRes.data || []);
        } catch (e) {
          setOriginCities([]);
        }
      }

      if (po.destination_country_id) {
        try {
          const citiesRes = await apiClient.get<{ success: boolean; data: City[] }>(
            `/api/master/cities?country_id=${po.destination_country_id}&limit=200`,
            { cache: 'no-store' }
          );
          setDestinationCities(citiesRes.data || []);
        } catch (e) {
          setDestinationCities([]);
        }
      }

      // ملء جميع البيانات تلقائياً من امر الشراء
      setFormData(prev => ({
        ...prev,
        purchase_order_id: po.id,
        // Project
        project_id: po.project_id || prev.project_id,
        // Vendor
        vendor_id: po.vendor_id,
        // Currency (use currency_id from PO)
        currency_id: po.currency_id || prev.currency_id,
        // Payment info
        payment_method: po.payment_method_name || po.payment_terms_name || prev.payment_method,
        total_amount: po.total_amount || 0,
        // Incoterm from delivery terms
        incoterm: po.incoterm || po.delivery_terms_name || prev.incoterm,
        // Origin location (country and city)
        origin_country_id: po.origin_country_id || prev.origin_country_id,
        origin_location_id: po.origin_city_id || prev.origin_location_id,
        // Destination location (country and city)
        destination_country_id: po.destination_country_id || prev.destination_country_id,
        destination_location_id: po.destination_city_id || prev.destination_location_id,
        // Ports
        port_of_loading_id: po.port_of_loading_id || prev.port_of_loading_id,
        port_of_loading_text: po.port_of_loading_text || prev.port_of_loading_text,
        port_of_discharge_id: po.port_of_discharge_id || prev.port_of_discharge_id,
        // Warehouse
        warehouse_id: po.warehouse_id || prev.warehouse_id,
      }));

      // Update selected currency code for exchange rate component
      if (po.currency_code) {
        setSelectedCurrencyCode(po.currency_code);
      }

      showToast('تم تحميل بيانات امر الشراء بنجاح', 'success');
    } catch (e: any) {
      showToast(e?.message || 'فشل تحميل بيانات امر الشراء', 'error');
    }
  };

  const validateForm = () => {
    const errors: Record<string, string> = {};

    if (!formData.shipment_number.trim()) errors.shipment_number = 'Shipment number is required';
    if (!formData.shipment_type_id) errors.shipment_type_id = 'Shipment type is required';
    if (!formData.project_id) errors.project_id = 'Project is required (shipment-centric architecture)';
    if (!formData.incoterm.trim()) errors.incoterm = 'Incoterm is required';

    // Either BL or AWB must be provided (backend validation requirement)
    if (!formData.bl_no.trim() && !formData.awb_no.trim()) {
      errors.bl_no = 'Either BL Number or AWB Number is required';
      errors.awb_no = 'Either BL Number or AWB Number is required';
    }

    // Port of loading is now OPTIONAL - can use free text or select from list
    // if (!formData.port_of_loading_id && !formData.port_of_loading_text.trim()) {
    //   errors.port_of_loading = 'Port of loading is required (select or enter)';
    // }
    if (!formData.port_of_discharge_id) errors.port_of_discharge_id = 'Port of discharge is required';
    
    // Countries are required now
    if (!formData.origin_country_id) errors.origin_country_id = 'Origin country is required';
    if (!formData.destination_country_id) errors.destination_country_id = 'Destination country is required';
    if (!formData.origin_location_id) errors.origin_location_id = 'Origin city is required';
    if (!formData.destination_location_id) errors.destination_location_id = 'Destination city is required';

    // تاريخ الوصول غير إلزامي الآن
    // if (!formData.expected_arrival_date) errors.expected_arrival_date = 'Expected arrival date is required';

    // إذا كانت طريقة الدفع اعتماد مستندي، رقم الاعتماد إلزامي
    if (formData.payment_method.toLowerCase().includes('lc') || formData.payment_method.toLowerCase().includes('اعتماد')) {
      if (!formData.lc_number.trim()) errors.lc_number = 'LC Number is required for Letter of Credit payments';
    }

    setFormErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!validateForm()) return;

    setLoading(true);
    try {
      // Validate numeric fields
      if (!formData.origin_location_id || isNaN(Number(formData.origin_location_id))) {
        showToast('Please select a valid origin city from the list', 'error');
        setLoading(false);
        return;
      }
      if (!formData.destination_location_id || isNaN(Number(formData.destination_location_id))) {
        showToast('Please select a valid destination city from the list', 'error');
        setLoading(false);
        return;
      }
      // Port of loading is optional now - can be null or free text
      if (!formData.port_of_discharge_id || isNaN(Number(formData.port_of_discharge_id))) {
        showToast('Please select a valid port of discharge', 'error');
        setLoading(false);
        return;
      }

      const payload = {
        shipment_number: formData.shipment_number.trim(),
        shipment_type_id: Number(formData.shipment_type_id),
        project_id: Number(formData.project_id),
        currency_id: formData.currency_id ? Number(formData.currency_id) : null,
        exchange_rate: parseFloat(formData.exchange_rate) || 1,
        incoterm: formData.incoterm.trim().toUpperCase(),
        bl_no: formData.bl_no.trim() || null,
        awb_no: formData.awb_no.trim() || null,
        origin_location_id: Number(formData.origin_location_id),
        destination_location_id: Number(formData.destination_location_id),
        expected_arrival_date: formData.expected_arrival_date || null,
        // Port of loading: use ID if selected, otherwise null (free text stored separately or ignored)
        port_of_loading_id: formData.port_of_loading_id ? Number(formData.port_of_loading_id) : null,
        port_of_loading_text: formData.port_of_loading_text?.trim() || null,
        port_of_discharge_id: Number(formData.port_of_discharge_id),
        payment_method: formData.payment_method.trim() || null,
        lc_number: formData.lc_number.trim() || null,
        total_amount: formData.total_amount ? Number(formData.total_amount) : null,
        warehouse_id: formData.warehouse_id ? Number(formData.warehouse_id) : null,
        vendor_id: formData.vendor_id ? Number(formData.vendor_id) : null,
        purchase_order_id: formData.purchase_order_id ? Number(formData.purchase_order_id) : null,
        notes: formData.notes.trim() || null,
        status_code: formData.status_code || null,
        stage_code: formData.stage_code || null,
      };

      // Debug: Log the payload
      console.log('=== SHIPMENT PAYLOAD ===');
      console.log(JSON.stringify(payload, null, 2));
      console.log('========================');

      let res: { success: boolean; data: any };
      
      // If PO is selected, use the from-purchase-order endpoint which also copies items
      if (formData.purchase_order_id) {
        console.log('Creating shipment from PO:', formData.purchase_order_id);
        res = await apiClient.post<{ success: boolean; data: { shipment: { id: number }; items_count: number } }>(
          `/api/logistics-shipments/from-purchase-order/${formData.purchase_order_id}`,
          payload
        );
        const shipmentData = res.data as { shipment: { id: number }; items_count: number };
        setNewShipmentId(shipmentData.shipment?.id ?? null);
        showToast(`Shipment created successfully with ${shipmentData.items_count || 0} items from PO`, 'success');
      } else {
        // Manual creation without PO
        res = await apiClient.post<{ success: boolean; data: { id: number } }>('/api/logistics-shipments', payload);
        setNewShipmentId(res.data?.id ?? null);
        showToast('Shipment created successfully', 'success');
      }
      
      setSuccess(true);
    } catch (err: any) {
      console.error('=== SHIPMENT ERROR ===');
      console.error('Full error:', err);
      console.error('Error data:', err?.data);
      console.error('Error message:', err?.data?.error?.message);
      console.error('Error details:');
      if (err?.data?.error?.details) {
        console.table(err.data.error.details);
        console.error('Details JSON:', JSON.stringify(err.data.error.details, null, 2));
      }
      console.error('======================');
      
      // Show detailed error message
      let errorMsg = err.message || 'Failed to create shipment';
      if (err?.data?.error?.details && Array.isArray(err.data.error.details)) {
        const detailMsgs = err.data.error.details.map((d: any) => 
          `${d.path?.join('.') || 'Field'}: ${d.message}`
        ).join('; ');
        errorMsg = `Validation failed: ${detailMsgs}`;
      }
      showToast(errorMsg, 'error');
    } finally {
      setLoading(false);
    }
  };

  if (success && newShipmentId) {
    return (
      <MainLayout>
        <Head>
          <title>Shipment Created - SLMS</title>
        </Head>

        <div className="max-w-2xl mx-auto py-12">
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8 text-center">
            <CheckCircleIcon className="w-16 h-16 text-green-500 mx-auto mb-4" />
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
              Shipment Created Successfully!
            </h1>
            <p className="text-gray-600 dark:text-gray-400 mb-6">
              Your shipment has been created and is ready for tracking.
            </p>

            <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4 mb-8">
              <p className="text-blue-800 dark:text-blue-400">
                <strong>Shipment ID:</strong> {newShipmentId}
              </p>
            </div>

            <div className="flex gap-4 justify-center">
              <Button
                onClick={() => router.push(`/shipments/${newShipmentId}`)}
                variant="primary"
              >
                View Shipment Details
              </Button>
              <Button onClick={() => router.push('/shipments')} variant="secondary">
                Back to Shipments
              </Button>
            </div>
          </div>
        </div>
      </MainLayout>
    );
  }

  return (
    <MainLayout>
      <Head>
        <title>Create Shipment - SLMS</title>
      </Head>

      {/* Header */}
      <div className="mb-8">
        <button
          onClick={() => router.push('/shipments')}
          className="flex items-center gap-2 text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 mb-4"
        >
          <ArrowLeftIcon className="w-5 h-5" />
          Back to Shipments
        </button>

        <div className="flex items-center gap-3">
          <PlusIcon className="w-8 h-8 text-blue-600" />
          <div>
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
              Create New Shipment
            </h1>
            <p className="text-gray-600 dark:text-gray-400 mt-1">
              إنشاء شحنة جديدة - Fill in the details to create a new shipment
            </p>
          </div>
        </div>
      </div>

      {/* Form Container */}
      <div className="max-w-4xl">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-8">
          <form onSubmit={handleSubmit} className="space-y-8">
            
            {/* Source Type Selection */}
            <div className="border-b border-gray-200 dark:border-gray-700 pb-6">
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
                مصدر البيانات | Data Source
              </h2>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {[
                  { value: 'manual', label: 'إدخال يدوي | Manual' },
                  { value: 'purchase_order', label: 'أمر شراء | Purchase Order' },
                  { value: 'rfq', label: 'عرض سعر | RFQ' },
                  { value: 'contract', label: 'عقد | Contract' },
                ].map((type) => (
                  <button
                    key={type.value}
                    type="button"
                    onClick={() => setFormData({ ...formData, source_type: type.value as any })}
                    className={`px-4 py-3 rounded-lg border-2 text-sm font-medium transition-all ${
                      formData.source_type === type.value
                        ? 'border-blue-600 bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300'
                        : 'border-gray-300 dark:border-gray-600 hover:border-blue-400'
                    }`}
                  >
                    {type.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Purchase Order Selection (if source_type is purchase_order) */}
            {formData.source_type === 'purchase_order' && (
              <div className="border-b border-gray-200 dark:border-gray-700 pb-6">
                <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
                  تحديد أمر الشراء | Select Purchase Order
                </h2>
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      أمر الشراء | Purchase Order *
                    </label>
                    <select
                      value={formData.purchase_order_id || ''}
                      onChange={(e) => {
                        const poId = e.target.value ? Number(e.target.value) : null;
                        if (poId) handlePOSelection(poId);
                      }}
                      className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="">-- اختر أمر شراء | Select PO --</option>
                      {purchaseOrders.map((po) => (
                        <option key={po.id} value={po.id}>
                          {po.order_number} - {po.vendor_display_name || po.vendor_name} ({po.total_amount} {po.currency_code})
                          {po.project_code ? ` [${po.project_code}]` : ''}
                        </option>
                      ))}
                    </select>
                  </div>

                  {selectedPO && (
                    <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
                      <h3 className="font-semibold text-blue-900 dark:text-blue-100 mb-2">
                        تفاصيل أمر الشراء | PO Details
                      </h3>
                      <div className="grid grid-cols-2 gap-3 text-sm">
                        <div className="bg-white dark:bg-gray-800 p-2 rounded">
                          <span className="font-medium text-gray-600 dark:text-gray-400 block text-xs">رقم الأمر (النظام) | System PO#</span>
                          <span className="font-bold text-blue-700 dark:text-blue-300">{selectedPO.order_number}</span>
                        </div>
                        <div className="bg-white dark:bg-gray-800 p-2 rounded">
                          <span className="font-medium text-gray-600 dark:text-gray-400 block text-xs">رقم أمر المورد | Vendor PO#</span>
                          <span className="font-bold text-purple-700 dark:text-purple-300">{selectedPO.vendor_contract_number || '-'}</span>
                        </div>
                        <div><span className="font-medium">المورد:</span> {selectedPO.vendor_display_name || selectedPO.vendor_name}</div>
                        <div><span className="font-medium">الإجمالي:</span> {selectedPO.total_amount} {selectedPO.currency_code}</div>
                        <div><span className="font-medium">طريقة الدفع:</span> {selectedPO.payment_method_name || selectedPO.payment_terms_name || selectedPO.payment_term_name || '-'}</div>
                        {selectedPO.project_id && (
                          <div className="col-span-2 bg-green-100 dark:bg-green-900/30 border border-green-300 dark:border-green-700 rounded p-2">
                            <span className="font-medium text-green-800 dark:text-green-200">المشروع | Project:</span>{' '}
                            <span className="text-green-900 dark:text-green-100">
                              {selectedPO.project_code} - {selectedPO.project_name}
                            </span>
                          </div>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Basic Information */}
            <div className="border-b border-gray-200 dark:border-gray-700 pb-6">
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
                معلومات أساسية | Basic Information
              </h2>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <Input
                    label="رقم الشحنة | Shipment Number *"
                    type="text"
                    placeholder="e.g., SHP-2024-001"
                    value={formData.shipment_number}
                    onChange={(e) => setFormData({ ...formData, shipment_number: e.target.value })}
                    error={formErrors.shipment_number}
                    required
                  />
                  {autoGeneratedNumber && (
                    <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                      💡 تسلسل تلقائي | Auto-generated (قابل للتعديل | Editable)
                    </p>
                  )}
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    نوع الشحنة | Shipment Type *
                  </label>
                  <select
                    value={formData.shipment_type_id}
                    onChange={(e) =>
                      setFormData({
                        ...formData,
                        shipment_type_id: e.target.value ? Number(e.target.value) : '',
                    })
                  }
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">اختر نوع | Select type</option>
                  {shipmentTypes
                    .filter((x) => x.is_active)
                    .map((st) => (
                      <option key={st.id} value={st.id}>
                        {st.code} - {st.name_en}
                      </option>
                    ))}
                </select>
                {formErrors.shipment_type_id && (
                  <p className="mt-1 text-sm text-red-500">{formErrors.shipment_type_id}</p>
                )}
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  المشروع | Project *
                </label>
                <select
                  value={formData.project_id}
                  disabled={formData.source_type === 'purchase_order' && !!selectedPO}
                  onChange={(e) => setFormData({ ...formData, project_id: e.target.value ? Number(e.target.value) : '' })}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 disabled:opacity-50"
                >
                  <option value="">اختر مشروع | Select Project</option>
                  {projects.map((proj) => (
                    <option key={proj.id} value={proj.id}>
                      {proj.code} - {proj.name_en} ({proj.project_type})
                    </option>
                  ))}
                </select>
                {formErrors.project_id && (
                  <p className="mt-1 text-sm text-red-500">{formErrors.project_id}</p>
                )}
              </div>

                <Input
                  label="Incoterm *"
                  type="text"
                  placeholder="e.g., FOB, CIF, EXW"
                  value={formData.incoterm}
                  onChange={(e) => setFormData({ ...formData, incoterm: e.target.value })}
                  error={formErrors.incoterm}
                  required
                />
              </div>
            </div>

            {/* Ports & Locations */}
            <div className="border-b border-gray-200 dark:border-gray-700 pb-6">
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
                الموانئ والمواقع | Ports & Locations
              </h2>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Origin Country */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    دولة المصدر | Origin Country *
                  </label>
                  <select
                    value={formData.origin_country_id}
                    onChange={(e) => handleOriginCountryChange(e.target.value ? Number(e.target.value) : 0)}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="">اختر الدولة | Select Country</option>
                    {countries.filter(c => c.is_active !== false).map((country) => (
                      <option key={country.id} value={country.id}>
                        {country.code} - {country.name_en || country.name} ({country.name_ar || country.name})
                      </option>
                    ))}
                  </select>
                  {formErrors.origin_country_id && (
                    <p className="mt-1 text-sm text-red-500">{formErrors.origin_country_id}</p>
                  )}
                </div>

                {/* Origin City */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    المدينة المصدرة | Origin City *
                  </label>
                  <select
                    value={formData.origin_location_id}
                    onChange={(e) => setFormData({ ...formData, origin_location_id: e.target.value ? Number(e.target.value) : '' })}
                    disabled={!formData.origin_country_id}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 disabled:opacity-50"
                  >
                    <option value="">اختر المدينة | Select City</option>
                    {originCities.filter(c => c.is_active).map((city) => (
                      <option key={city.id} value={city.id}>
                        {city.code} - {city.name_en || city.name} ({city.name_ar || ''})
                      </option>
                    ))}
                  </select>
                  {formErrors.origin_location_id && (
                    <p className="mt-1 text-sm text-red-500">{formErrors.origin_location_id}</p>
                  )}
                </div>

                {/* Destination Country (Saudi Arabia default) */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    دولة الوصول | Destination Country * <span className="text-blue-500">(السعودية افتراضياً)</span>
                  </label>
                  <select
                    value={formData.destination_country_id}
                    onChange={(e) => handleDestinationCountryChange(e.target.value ? Number(e.target.value) : 0)}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="">اختر الدولة | Select Country</option>
                    {countries.filter(c => c.is_active !== false).map((country) => (
                      <option key={country.id} value={country.id}>
                        {country.code} - {country.name_en || country.name} ({country.name_ar || country.name})
                      </option>
                    ))}
                  </select>
                  {formErrors.destination_country_id && (
                    <p className="mt-1 text-sm text-red-500">{formErrors.destination_country_id}</p>
                  )}
                </div>

                {/* Destination City */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    مدينة الوجهة | Destination City *
                  </label>
                  <select
                    value={formData.destination_location_id}
                    onChange={(e) => setFormData({ ...formData, destination_location_id: e.target.value ? Number(e.target.value) : '' })}
                    disabled={!formData.destination_country_id}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 disabled:opacity-50"
                  >
                    <option value="">اختر المدينة | Select City</option>
                    {destinationCities.filter(c => c.is_active).map((city) => (
                      <option key={city.id} value={city.id}>
                        {city.code} - {city.name_en || city.name} ({city.name_ar || ''})
                      </option>
                    ))}
                  </select>
                  {formErrors.destination_location_id && (
                    <p className="mt-1 text-sm text-red-500">{formErrors.destination_location_id}</p>
                  )}
                </div>

                {/* Port of Loading (Optional with free text) */}
                <div className="md:col-span-2">
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    ميناء الشحن | Port of Loading <span className="text-gray-400">(اختياري - يمكن الكتابة)</span>
                  </label>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                    <select
                      value={formData.port_of_loading_id}
                      onChange={(e) => setFormData({ ...formData, port_of_loading_id: e.target.value ? Number(e.target.value) : '', port_of_loading_text: '' })}
                      className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="">اختر ميناء من القائمة | Select from list</option>
                      {ports.map((port) => (
                        <option key={port.id} value={port.id}>
                          {port.port_type === 'sea' ? '🚢' : port.port_type === 'air' ? '✈️' : '🚚'} {port.name_en} - {port.name_ar} ({port.country_name_ar || ''})
                        </option>
                      ))}
                    </select>
                    <Input
                      type="text"
                      placeholder="أو اكتب اسم الميناء العالمي | Or type any port name"
                      value={formData.port_of_loading_text}
                      onChange={(e) => setFormData({ ...formData, port_of_loading_text: e.target.value, port_of_loading_id: '' })}
                    />
                  </div>
                </div>

                {/* Port of Discharge (Required) */}
                <div className="md:col-span-2">
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    ميناء الوصول | Port of Discharge * <span className="text-blue-500">(الموانئ والمطارات السعودية)</span>
                  </label>
                  <select
                    value={formData.port_of_discharge_id}
                    onChange={(e) => setFormData({ ...formData, port_of_discharge_id: e.target.value ? Number(e.target.value) : '' })}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="">اختر ميناء الوصول | Select Port of Discharge</option>
                    {ports.map((port) => (
                      <option key={port.id} value={port.id}>
                        {port.port_type === 'sea' ? '🚢 ميناء بحري' : port.port_type === 'air' ? '✈️ مطار' : '🚚 منفذ بري'} - {port.name_ar} ({port.name_en})
                      </option>
                    ))}
                  </select>
                  {formErrors.port_of_discharge_id && (
                    <p className="mt-1 text-sm text-red-500">{formErrors.port_of_discharge_id}</p>
                  )}
                </div>
              </div>
            </div>

            {/* Status & Stage */}
            <div className="border-b border-gray-200 dark:border-gray-700 pb-6">
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
                حالة الشحنة ومراحلها | Status & Stage
              </h2>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    حالة الشحنة | Shipment Status
                  </label>
                  <select
                    value={formData.status_code}
                    onChange={(e) => setFormData({ ...formData, status_code: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="">اختر الحالة | Select Status</option>
                    {shipmentStatuses.map((status) => (
                      <option key={status.id} value={status.code}>
                        {status.code} - {status.name_ar} ({status.name_en})
                      </option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    مرحلة الشحنة | Shipment Stage
                  </label>
                  <select
                    value={formData.stage_code}
                    onChange={(e) => setFormData({ ...formData, stage_code: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="">اختر المرحلة | Select Stage</option>
                    {shipmentStages.map((stage) => (
                      <option key={stage.id} value={stage.code}>
                        {stage.code} - {stage.name_ar} ({stage.name_en})
                      </option>
                    ))}
                  </select>
                </div>
              </div>
            </div>

            {/* Documents */}
            <div className="border-b border-gray-200 dark:border-gray-700 pb-6">
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
                المستندات | Documents
              </h2>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Input
                  label="رقم البوليصة | BL No (Optional)"
                  type="text"
                  placeholder="Bill of Lading"
                  value={formData.bl_no}
                  onChange={(e) => setFormData({ ...formData, bl_no: e.target.value })}
                  error={formErrors.bl_no}
                />
                <Input
                  label="رقم بوليصة الشحن الجوي | AWB No (Optional)"
                  type="text"
                  placeholder="Air Waybill"
                  value={formData.awb_no}
                  onChange={(e) => setFormData({ ...formData, awb_no: e.target.value })}
                />
                <Input
                  label="تاريخ الوصول المتوقع | Expected Arrival (Optional)"
                  type="date"
                  value={formData.expected_arrival_date}
                  onChange={(e) => setFormData({ ...formData, expected_arrival_date: e.target.value })}
                />
              </div>
            </div>

            {/* Payment Information */}
            <div className="border-b border-gray-200 dark:border-gray-700 pb-6">
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
                معلومات الدفع | Payment Information
              </h2>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Currency */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    العملة | Currency
                  </label>
                  <CurrencySelector
                    value={formData.currency_id ? Number(formData.currency_id) : null}
                    onChange={(id) => setFormData({ ...formData, currency_id: id || '' })}
                    onCurrencyCodeChange={setSelectedCurrencyCode}
                    companyId={getCompanyId()}
                  />
                </div>

                {/* Exchange Rate - only shows when currency differs from base */}
                <ExchangeRateField
                  currencyCode={selectedCurrencyCode}
                  value={formData.exchange_rate}
                  onChange={(value) => setFormData({ ...formData, exchange_rate: value })}
                  hideWhenBaseCurrency={true}
                  label="سعر الصرف | Exchange Rate"
                />

                <Input
                  label="طريقة الدفع | Payment Method"
                  type="text"
                  placeholder="e.g., LC, TT, Cash"
                  value={formData.payment_method}
                  disabled={formData.source_type === 'purchase_order' && !!selectedPO}
                  onChange={(e) => setFormData({ ...formData, payment_method: e.target.value })}
                />

                {(formData.payment_method.toLowerCase().includes('lc') || formData.payment_method.toLowerCase().includes('اعتماد')) && (
                  <Input
                    label="رقم الاعتماد المستندي | LC Number *"
                    type="text"
                    placeholder="LC-2024-001"
                    value={formData.lc_number}
                    onChange={(e) => setFormData({ ...formData, lc_number: e.target.value })}
                    error={formErrors.lc_number}
                    required
                  />
                )}

                <Input
                  label="المبلغ الإجمالي | Total Amount"
                  type="number"
                  placeholder="0.00"
                  value={formData.total_amount}
                  disabled={formData.source_type === 'purchase_order' && !!selectedPO}
                  onChange={(e) => setFormData({ ...formData, total_amount: Number(e.target.value) })}
                />
              </div>
            </div>

            {/* Items from PO */}
            {selectedPO && poItems.length > 0 && (
              <div className="border-b border-gray-200 dark:border-gray-700 pb-6">
                <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
                  أصناف أمر الشراء | PO Items ({poItems.length})
                </h2>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead className="bg-gray-50 dark:bg-gray-700">
                      <tr>
                        <th className="px-3 py-2 text-left">#</th>
                        <th className="px-3 py-2 text-left">SKU</th>
                        <th className="px-3 py-2 text-left">الصنف | Item</th>
                        <th className="px-3 py-2 text-left">الاسم العربي | Arabic Name</th>
                        <th className="px-3 py-2 text-right">الكمية | Qty</th>
                        <th className="px-3 py-2 text-left">الوحدة | Unit</th>
                        <th className="px-3 py-2 text-right">السعر | Price</th>
                        <th className="px-3 py-2 text-right">الإجمالي | Total</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                      {poItems.map((item, idx) => (
                        <tr key={item.id} className="hover:bg-gray-50 dark:hover:bg-gray-700/50">
                          <td className="px-3 py-2 text-gray-500">{idx + 1}</td>
                          <td className="px-3 py-2 font-mono text-xs">{item.sku}</td>
                          <td className="px-3 py-2">{item.name_en}</td>
                          <td className="px-3 py-2 text-gray-600 dark:text-gray-400">{item.name_ar}</td>
                          <td className="px-3 py-2 text-right font-medium">{Number(item.quantity).toLocaleString()}</td>
                          <td className="px-3 py-2">{item.unit_code}</td>
                          <td className="px-3 py-2 text-right">{Number(item.unit_price).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 4 })}</td>
                          <td className="px-3 py-2 text-right font-semibold text-blue-600 dark:text-blue-400">
                            {(Number(item.unit_price) * Number(item.quantity)).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                          </td>
                        </tr>
                      ))}
                      <tr className="bg-gray-100 dark:bg-gray-700 font-semibold">
                        <td colSpan={6} className="px-3 py-2 text-right">المجموع الكلي | Grand Total:</td>
                        <td colSpan={2} className="px-3 py-2 text-right text-lg text-blue-600 dark:text-blue-400">
                          {/* استخدام الإجمالي الفعلي من أمر الشراء */}
                          {selectedPO?.total_amount 
                            ? Number(selectedPO.total_amount).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })
                            : poItems.reduce((sum, item) => sum + (Number(item.unit_price) * Number(item.quantity)), 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })
                          } {selectedPO?.currency_code || ''}
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Additional Info */}
            <div>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
                معلومات إضافية | Additional Information
              </h2>

              <div>
                <WarehouseSelector
                  value={formData.warehouse_id}
                  onChange={(val) => setFormData({ ...formData, warehouse_id: val })}
                  label="المستودع | Warehouse"
                />
              </div>

              <div className="mt-4">
                <Input
                  label="ملاحظات | Notes"
                  multiline
                  rows={4}
                  placeholder="أي ملاحظات إضافية..."
                  value={formData.notes}
                  onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                />
              </div>
            </div>

            {/* Submit Buttons */}
            <div className="flex gap-4 pt-6 border-t border-gray-200 dark:border-gray-700">
              <Button type="submit" variant="primary" loading={loading} disabled={loading}>
                إنشاء الشحنة | Create Shipment
              </Button>
              <Button
                type="button"
                variant="secondary"
                onClick={() => router.push('/shipments')}
                disabled={loading}
              >
                إلغاء | Cancel
              </Button>
            </div>
          </form>
        </div>
      </div>
    </MainLayout>
  );
}

export default withPermission(MenuPermissions.Logistics.Shipments.Create, CreateShipmentPage);
